config/routes.rb
Rails.application.routes.draw do
  resources :story_tasks
  root 'welcome#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations:   'users/invitations'
  }

  namespace :admin, as: nil do
    get 'dashboard', to: 'dashboard#show'
    get 'profile', to: 'profiles#show', as: :profile
    resources :projects, except: [:index] do
      resources :tags, only: [:index]
      resources :iterations, only: [:update] do
        collection do
          get 'done', to: 'iterations#index'
        end

        member do
          put 'finish', to: 'iterations#finish'
        end
      end
      patch 'stories/positions', to: 'positions#update'
      resources :stories do
        resources :comments, only: [:create, :update]

        member do
          patch :estimate, to: 'estimations#update'
          Story.aasm.events.map(&:name).each do |event|
            patch event, to: "stories_states##{event}"
          end
        end
      end
    end
    resources :tasks
    resources :accounts, except: [:show] do
      resources :invitation, only: [:new, :create, :update], controller: 'users/invitations', as: 'user_invitations'
    end
    resources :accounts_users, only: [:destroy]
  end

  mount ActionCable.server, at: '/cable'
end

app/models/iteration.rb
# == Schema Information
#
# Table name: iterations
#
#  id         :integer          not null, primary key
#  start_date :date
#  end_date   :date
#  project_id :integer
#  velocity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  number     :integer
#
# Indexes
#
#  index_iterations_on_project_id  (project_id)
#

class Iteration < ApplicationRecord
  belongs_to :project
  has_many :stories, dependent: :destroy

  scope :active,  ->() { where('? <= end_date', Date.today) }
  scope :done,    ->() { where('? > end_date', Date.today) }
  scope :from_id, ->(id) { where('id > ?', id) }

  accepts_nested_attributes_for :stories

  def self.current
    active.find_by('start_date <= ?', Date.today)
  end

  def current?
    (start_date...end_date).include? Date.today
  end

  def total_points
    stories.estimated.sum(:points)
  end

  def points_done
    stories.estimated.accepted.sum(:points)
  end

  def count_story_done
    stories.done.count
  end

  def story_fits?(story)
    !story.estimated? || (story.points + total_points) <= velocity
  end
end

app/controllers/admin/iterations_controller.rb
module Admin
  class IterationsController < BaseController
    def index
      @iterations = project.iterations.done
    end

    def update
      project.update(project_params)
      project.update_iterations_from(iteration)

      redirect_to project
    end

    def finish
      FinishIteration.call(iteration)

      redirect_to done_project_iterations_path, notice: "Iteration No. #{iteration.number} has finished."
    end

    private

    def iteration
      @iteration ||= project.iterations.find(params[:id])
    end

    def project
      @project ||= current_user.projects.find(params[:project_id])
    end

    def project_params
      params.require(:project).permit(:iteration_duration_in_weeks)
    end
  end
end

app/helpers/iterations_helper.rb
module IterationsHelper
  MAX_NUMBER_ACCEPTED_STORIES = 3.freeze

  def iteration_classes(iteration)
    classes = []
    classes << 'Iteration--collapsed' unless iteration.current?
    classes << 'Iteration--hide-accepted' if iteration.count_story_done > MAX_NUMBER_ACCEPTED_STORIES
    classes.join(' ')
  end
end

app/views/admin/iterations/_done_iterations.html.erb
<% iterations.each do |iteration| %>
  <div class="row">
    <div class="col-md-12">
      <div class="card Iteration Iteration--done Iteration--collapsed" data-id="<%= iteration.id %>">
        <div class="table-responsive">
          <table class="table card-table">
            <thead>
              <tr>
                <th colspan="4">
                  <a href="" class="Iteration-collapsable-button" data-toggle="iteration-collapse">
                    <i class="fa fa-caret-down"></i>
                  </a>
                  <small class="Iteration-title">
                    <%= iteration.number %> -
                    <%= "#{iteration.start_date.strftime('%b %e')} - #{iteration.end_date.strftime('%b %e')}" %> -
                    <%= "#{iteration.points_done} of #{iteration.total_points}" %> -
                    Velocity <%= iteration.velocity %>
                  </small>
                </th>
                <th style="width: 13%" class="text-right">
                  <%= link_to 'Finish', finish_project_iteration_path(iteration.project, iteration), class: 'btn btn-sm btn-primary', method: :put %>
                </th>
              </tr>
            </thead>
            <tbody>
              <%= render collection: iteration.stories.order(:position), as: :story, partial: 'admin/projects/story' %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/iterations/index.html.erb
<div class="page-header">
  <h1 class="page-title">
    Project: <%= @project.name %> - Done Iterations
  </h1>
  <div class="page-options d-flex">
    <%= link_to 'New Story', new_project_story_path(@project), class: 'btn btn-secondary' %>
    <%= link_to 'Active', @project, class: 'btn btn-secondary' %>
  </div>
</div>

<%= render 'done_iterations', iterations: @iterations %> <br>