config/routes.rb
Rails.application.routes.draw do
  resources :story_tasks
  root 'welcome#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations:   'users/invitations'
  }

  namespace :admin, as: nil do
    get 'dashboard', to: 'dashboard#show'
    get 'profile', to: 'profiles#show', as: :profile
    resources :projects, except: [:index] do
      resources :tags, only: [:index]
      resources :iterations, only: [:update] do
        collection do
          get 'done', to: 'iterations#index'
        end

        member do
          put 'finish', to: 'iterations#finish'
        end
      end
      patch 'stories/positions', to: 'positions#update'
      resources :stories do
        resources :comments, only: [:create, :update]

        member do
          patch :estimate, to: 'estimations#update'
          Story.aasm.events.map(&:name).each do |event|
            patch event, to: "stories_states##{event}"
          end
        end
      end
    end
    resources :tasks
    resources :accounts, except: [:show] do
      resources :invitation, only: [:new, :create, :update], controller: 'users/invitations', as: 'user_invitations'
    end
    resources :accounts_users, only: [:destroy]
  end

  mount ActionCable.server, at: '/cable'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Account < ApplicationRecord
  has_many :accounts_users
  has_many :users, through: :accounts_users
  has_many :projects

  validates :name, presence: true

  scope :owned_by, ->(user) { joins(:users).where(users: {id: user.id}).merge(AccountsUser.admins) }
  scope :belongs,  ->(user) { joins(:users).where(users: {id: user.id}).merge(AccountsUser.users) }

  def admin
    accounts_users.admin.user
  end
  delegate :email, to: :admin, prefix: true

  def count_users
    accounts_users.users.count
  end
end

app/controllers/admin/accounts_controller.rb
module Admin
  class AccountsController < BaseController
    before_action :set_account, only: [:show, :edit, :update, :destroy]

    # GET /accounts
    # GET /accounts.json
    def index
      @accounts_owned_by_me = Account.owned_by(current_user)
      @accounts             = Account.belongs(current_user)
    end

    # GET /accounts/new
    def new
      @account = Account.new
    end

    # GET /accounts/1/edit
    def edit
    end

    # POST /accounts
    def create
      @account = ::NewAccountBuilder.new
                                    .assign_attributes(account_params)
                                    .set_owner(current_user)
                                    .build

      respond_to do |format|
        if @account.save
          format.html { redirect_to accounts_path, notice: 'Account was successfully created.' }
          format.json { render :show, status: :created, location: @account }
        else
          format.html { render :new }
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      return render(:edit) unless @account.update(account_params)
      redirect_to accounts_path, notice: 'Account was successfully updated.'
    end

    # DELETE /accounts/1
    # DELETE /accounts/1.json
    def destroy
      @account.destroy
      redirect_to accounts_url, notice: 'Account was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_account
        @account = Account.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def account_params
        params.require(:account).permit(:name)
      end
  end
end

app/views/admin/accounts/_account.html.erb
<tr>
  <td><%= account.name %></td>
  <td><%= link_to account.admin_email, user_profile_path(account.admin) %></td>
  <td><%= account.count_users %></td>
  <td><%= link_to 'Show', account %></td>
  <td><%= link_to 'Edit', edit_account_path(account) %></td>
  <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/accounts/_accounts.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title"> <%= account.name %> </div>
        <div class="card-options">
          <a class="btn btn-secondary btn-sm">Edit</a>
          <%= link_to 'Add Colaborator', new_account_user_invitation_path(account), class: 'btn btn-secondary btn-sm ml-3' %>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <%= render collection: account.projects, as: :project, partial: 'project' %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/accounts/_detail.html.erb
<fieldset>
  <legend>Detail</legend>
  <dl>
    <dt>Name:</dt>
    <dd><%= account.name %></dd>
  </dl>
</fieldset>

app/views/admin/accounts/_form.html.erb
<%= form_with(model: account, local: true, html: {class: 'card'}) do |form| %>
  <%= render 'admin/shared/model_card_error', model: account %>

  <div class="card-body">
    <div class="form-group">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, id: :account_name, class: 'form-control' %>
    </div>
  </div>

  <div class="card-footer text-right">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/accounts/_project.html.erb
<tr>
  <td> <%= link_to project.name, project %> </td>
  <td style="width: 15%;"> <%= project.count_stories %> stories </td>
  <td style="width: 15%;"> <%= project.count_collaborators %> collaborators</td>
</tr>

app/views/admin/accounts/_user.html.erb
<tr>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
</tr>

app/views/admin/accounts/edit.html.erb
<div class="page-header">
  <h1 class="page-title">
    Edditing Account
  </h1>
</div>

<%= render 'form', account: @account %>

app/views/admin/accounts/index.html.erb
<div class="page-header">
  <h1 class="page-title"> Accounts you Own </h1>
  <div class="page-options d-flex">
    <%= link_to 'New Account', new_account_path, class: 'btn btn-secondary' %>
  </div>
</div>

<%= render collection: @accounts_owned_by_me, as: :account, partial: 'accounts' %>

<div class="page-header">
  <h1 class="page-title"> Accounts you Belong </h1>
</div>

<%= render collection: @accounts, as: :account, partial: 'accounts' %>

app/views/admin/accounts/new.html.erb
<div class="page-header">
  <h1 class="page-title">
    New Account
  </h1>
</div>

<%= render 'form', account: @account %>

app/views/admin/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'detail', account: @account %>
<%#= render 'users', companies_users: @account.companies_users %>
<%= render 'projects', projects: @account.projects %>

<br>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', companies_path %>