config/routes.rb
Rails.application.routes.draw do
  resources :story_tasks
  root 'welcome#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations:   'users/invitations'
  }

  namespace :admin, as: nil do
    get 'dashboard', to: 'dashboard#show'
    get 'profile', to: 'profiles#show', as: :profile
    resources :projects, except: [:index] do
      resources :tags, only: [:index]
      resources :iterations, only: [:update] do
        collection do
          get 'done', to: 'iterations#index'
        end

        member do
          put 'finish', to: 'iterations#finish'
        end
      end
      patch 'stories/positions', to: 'positions#update'
      resources :stories do
        resources :comments, only: [:create, :update]

        member do
          patch :estimate, to: 'estimations#update'
          Story.aasm.events.map(&:name).each do |event|
            patch event, to: "stories_states##{event}"
          end
        end
      end
    end
    resources :tasks
    resources :accounts, except: [:show] do
      resources :invitation, only: [:new, :create, :update], controller: 'users/invitations', as: 'user_invitations'
    end
    resources :accounts_users, only: [:destroy]
  end

  mount ActionCable.server, at: '/cable'
end

app/models/story_task.rb
# == Schema Information
#
# Table name: story_tasks
#
#  id          :integer          not null, primary key
#  description :text
#  done        :boolean          default("false")
#  story_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_story_tasks_on_story_id  (story_id)
#

class StoryTask < ApplicationRecord
  belongs_to :story
end

app/controllers/story_tasks_controller.rb
class StoryTasksController < ApplicationController
  before_action :set_story_task, only: [:show, :edit, :update, :destroy]

  # GET /story_tasks
  def index
    @story_tasks = StoryTask.all
  end

  # GET /story_tasks/1
  def show
  end

  # GET /story_tasks/new
  def new
    @story_task = StoryTask.new
  end

  # GET /story_tasks/1/edit
  def edit
  end

  # POST /story_tasks
  def create
    @story_task = StoryTask.new(story_task_params)

    if @story_task.save
      redirect_to @story_task, notice: 'Story task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /story_tasks/1
  def update
    if @story_task.update(story_task_params)
      redirect_to @story_task, notice: 'Story task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /story_tasks/1
  def destroy
    @story_task.destroy
    redirect_to story_tasks_url, notice: 'Story task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story_task
      @story_task = StoryTask.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def story_task_params
      params.require(:story_task).permit(:description, :done)
    end
end

app/helpers/story_tasks_helper.rb
module StoryTasksHelper
end

app/views/admin/story_tasks/_form.html.erb
<%= form_with(model: story_task, local: true) do |form| %>
  <% if story_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story_task.errors.count, "error") %> prohibited this story_task from being saved:</h2>

      <ul>
      <% story_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :story_task_description %>
  </div>

  <div class="field">
    <%= form.label :done %>
    <%= form.check_box :done, id: :story_task_done %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/story_tasks/edit.html.erb
<h1>Editing Story Task</h1>

<%= render 'form', story_task: @story_task %>

<%= link_to 'Show', @story_task %> |
<%= link_to 'Back', story_tasks_path %>

app/views/admin/story_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Story Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @story_tasks.each do |story_task| %>
      <tr>
        <td><%= story_task.description %></td>
        <td><%= story_task.done %></td>
        <td><%= link_to 'Show', story_task %></td>
        <td><%= link_to 'Edit', edit_story_task_path(story_task) %></td>
        <td><%= link_to 'Destroy', story_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story Task', new_story_task_path %>

app/views/admin/story_tasks/new.html.erb
<h1>New Story Task</h1>

<%= render 'form', story_task: @story_task %>

<%= link_to 'Back', story_tasks_path %>

app/views/admin/story_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @story_task.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @story_task.done %>
</p>

<%= link_to 'Edit', edit_story_task_path(@story_task) %> |
<%= link_to 'Back', story_tasks_path %>