config/routes.rb
Rails.application.routes.draw do
  resources :story_tasks
  root 'welcome#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations:   'users/invitations'
  }

  namespace :admin, as: nil do
    get 'dashboard', to: 'dashboard#show'
    get 'profile', to: 'profiles#show', as: :profile
    resources :projects, except: [:index] do
      resources :tags, only: [:index]
      resources :iterations, only: [:update] do
        collection do
          get 'done', to: 'iterations#index'
        end

        member do
          put 'finish', to: 'iterations#finish'
        end
      end
      patch 'stories/positions', to: 'positions#update'
      resources :stories do
        resources :comments, only: [:create, :update]

        member do
          patch :estimate, to: 'estimations#update'
          Story.aasm.events.map(&:name).each do |event|
            patch event, to: "stories_states##{event}"
          end
        end
      end
    end
    resources :tasks
    resources :accounts, except: [:show] do
      resources :invitation, only: [:new, :create, :update], controller: 'users/invitations', as: 'user_invitations'
    end
    resources :accounts_users, only: [:destroy]
  end

  mount ActionCable.server, at: '/cable'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                          :integer          not null, primary key
#  name                        :string
#  description                 :text
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  account_id                  :integer
#  velocity                    :integer          default("10")
#  iteration_duration_in_weeks :integer          default("1")
#
# Indexes
#
#  index_projects_on_account_id  (account_id)
#

class Project < ApplicationRecord
  EXTRA_DAY_TO_COMPLETE_WEEK = 1

  belongs_to :account

  has_many :iterations, dependent: :destroy
  has_many :stories, -> { order(position: :asc) }, through: :iterations
  has_many :labels, through: :stories
  has_many :story_states

  accepts_nested_attributes_for :iterations

  has_many :collaborators, through: :stories, class_name: 'User', source: :owners

  validates :name, presence: true

  def progress
    total_features = stories.features.count.to_f
    return 0 if total_features == 0.0
    accepted_stories = stories.features.accepted.count.to_f
    (accepted_stories / total_features * 100.0).to_i
  end

  def active_iterations
    iterations.active
  end

  def current_iteration
    iterations.current || create_current_iteration
  end

  def avg_velocity
    avg_no_iterations = 3
    (iterations.last(avg_no_iterations).sum(&:velocity) / avg_no_iterations).to_i
  end

  def count_collaborators
    collaborators.count
  end

  def count_stories
    stories.count
  end

  def update_iterations_from(init_iteration)
    init_iteration.update(end_date: init_iteration.start_date + iteration_duration_in_weeks.week - EXTRA_DAY_TO_COMPLETE_WEEK.day)
    active_iterations
      .from_id(init_iteration.id)
      .order(:id)
      .inject(init_iteration) do |prev_iteration, iteration|
        start_date = prev_iteration.end_date + 1.day
        end_date   = start_date + iteration_duration_in_weeks.week - EXTRA_DAY_TO_COMPLETE_WEEK.day
        iteration.update(start_date: start_date, end_date: end_date)
        iteration
    end
  end

  def find_next_iteration_for_story(story)
    active_iterations.find { |iteration| iteration.story_fits?(story) } ||
      build_iteration_from_last_iteration ||
      build_first_iteration
  end

  def build_iteration_from_last_iteration
    iteration = iterations.order(number: :desc).first
    return unless iteration
    day_diff = (iteration.end_date - iteration.start_date).to_i + EXTRA_DAY_TO_COMPLETE_WEEK
    iterations.build(start_date: iteration.start_date + day_diff.days, end_date: iteration.end_date + day_diff.days, velocity: iteration.velocity, number: iteration.number + 1)
  end

  def create_current_iteration
    iteration = build_iteration_from_last_iteration || build_first_iteration
    iteration.save && iteration
  end

  def build_first_iteration
    start_date = Date.today.beginning_of_week
    end_date   = start_date + iteration_duration_in_weeks.week - EXTRA_DAY_TO_COMPLETE_WEEK.day
    iterations.build(start_date: start_date, end_date: end_date, velocity: velocity, number: 1)
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < BaseController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :set_accounts, only: [:new, :create, :edit, :update]

    # GET /projects/1
    def show
      @active_iterations = @project.active_iterations.includes(stories: [:requester, :owners, :labels])
    end

    # GET /projects/new
    def new
      @project = Project.new
    end

    # GET /projects/1/edit
    def edit
    end

    # POST /projects
    def create
      @project = Project.new(project_params)
      return render(:new) unless @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    end

    # PATCH/PUT /projects/1
    def update
      if @project.update(project_params)
        redirect_to @project, notice: 'Project was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /projects/1
    def destroy
      @project.destroy
      redirect_to dashboard_url, notice: 'Project was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def project_params
        params.require(:project).permit(:name, :description, :account_id)
      end

      def set_accounts
        @accounts = current_user.accounts.pluck(:name, :id)
      end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def progress_color(progress)
    case progress
    when 0..40 then 'bg-red'
    when 41..80 then 'bg-yellow'
    when 81..1000 then 'bg-green'
    end
  end
end

app/views/admin/projects/_detail.html.erb
<fieldset>
  <legend>Detail</legend>
  <dl>
    <dt>Name:</dt>
    <dd><%= project.name %></dd>
    <dt>Description:</dt>
    <dd><%= project.description %></dd>
    <dt>Story States</dt>
    <dd><%= project.story_states.collect {|ss| ss.display_name }.join(' | ') %></dd>
    <dt>Story Types</dt>
    <dd><%= StoryType.all.collect {|st| st.display_name }.join(' | ') %></dd>
  </dl>
</fieldset>

app/views/admin/projects/_form.html.erb
<%= form_with(model: project, local: true, html: {class: 'card'}) do |form| %>
  <%= render 'admin/shared/model_card_error', model: project %>

  <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, id: :project_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description, class: 'form-label' %>
          <%= form.text_area :description, id: :project_description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :account_id, class: 'form-label' %>
          <%= form.select :account_id, @accounts, {}, id: :project_account, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer text-right">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/projects/_iteration.html.erb
<div class="card Iteration <%= iteration_classes(iteration) %>" data-id="<%= iteration.id %>" id="Iteration-<%= iteration.id %>">
  <div class="table-responsive">
    <table class="table card-table">
      <thead>
        <tr>
          <th colspan="5">
            <a href="" class="Iteration-collapsable-button" data-toggle="iteration-collapse">
              <i class="fa fa-caret-down"></i>
            </a>
            <small>
              <%= iteration.number %> -
              <%= render 'admin/projects/iteration_dates_form', iteration: iteration %> - <%= "#{iteration.points_done} of #{iteration.total_points}" %> - Velocity <%= iteration.velocity %>

            </small>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr class="Iteration-toggle-accepted-row Iteration-accepted-stories-row">
          <td colspan="5">Accepted Stories: <%= iteration.count_story_done %></td>
        </tr>
        <tr class="Iteration-toggle-accepted-row Iteration-hide-accepted-stories-row">
          <td colspan="5">Hide Accepted Stories: <%= iteration.count_story_done %></td>
        </tr>
        <%= render collection: iteration.stories.order(:position), as: :story, partial: 'admin/projects/story' %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/projects/_iteration_dates_form.erb
<div class="dropdown">
  <span class="dropdown-toggle" data-toggle="dropdown">
     <%= "#{iteration.start_date.strftime('%b %e')} - #{iteration.end_date.strftime('%b %e')}" %>
  </span>
  <div class="dropdown-menu">
    <%= form_for iteration.project, url: [iteration.project, iteration], method: :put do |f| %>
      <%= f.label 'Duration in weeks', class: 'form-label' %>
      <div class="input-group">
        <%= f.text_field :iteration_duration_in_weeks, class: 'form-control' %>
        <div class="input-group-append">
          <%= f.submit 'Change', class: 'btn btn-primary btn-block'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/projects/_project.html.erb
<tr>
  <td>
    <strong><%= project.name %></strong> <br>
    <em><%= project.description %></em>
  </td>
  <td><%= project.worked %></td>
  <td><%= project.billed %></td>
  <td><%= link_to 'Show', project %></td>
  <td><%= link_to 'Edit', edit_project_path(project) %></td>
  <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/projects/_story.html.erb
<tr
  id="Story-<%= story.id %>"
  class="Story <%= story_classes(story) %>"
  data-position="<%= story.position %>"
  data-data="<%= story.to_json(only: [:id, :position, :iteration_id, :project_id]) %>"
  draggable="<%= !story.last_status? %>">
  <td style="width: 1%;"><%= story_type_icon(story.story_type) %></td>
  <td style="width: 1%;"><%= story.points if story.estimated? %></td>
  <td style="width: 1%;">
    <% if story.comments? %> <i class="fa fa-comment"></i> <% end %>
  </td>
  <td>
    <%= link_to story.title, project_story_path(@project, story), class: 'Story-title' %>
    <% if story.owners.any? %>
      <span class="Story-owners">( <%= owner_list_links(story) %> )</span>
    <% end %>
    <br /> <%= label_list_links(story) %>
    </td>
  <td style="width: 14%;" class="text-right"><%= story_action_button(story) %></td>
</tr>

app/views/admin/projects/_velocity_form.html.erb
<div class="dropdown">
  <span class="dropdown-toggle" data-toggle="dropdown">
     <%= iteration.velocity %>
  </span>
  <div class="dropdown-menu">
    <%= form_for [iteration.project, iteration], method: :put do |f| %>
      <div class="input-group">
        <%= f.text_field :velocity, class: 'form-control' %>
        <div class="input-group-append">
          <%= f.submit 'Change', class: 'btn btn-primary btn-block'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/projects/edit.html.erb
<div class="page-header">
  <h1 class="page-title">
    Editing Project
  </h1>
</div>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %>

app/views/admin/projects/new.html.erb
<div class="page-header">
  <h1 class="page-title">
    New Project
  </h1>
</div>

<%= render 'form', project: @project %>

app/views/admin/projects/show.html.erb
<div class="Project" data-id="<%= @project.id %>">
  <div class="page-header">
    <h1 class="page-title">
      Project: <%= @project.name %>
    </h1>
    <div class="page-options d-flex">
      <%= link_to 'New Story', new_project_story_path(@project), class: 'btn btn-secondary' %>
      <%= link_to 'Done', done_project_iterations_path(@project), class: 'btn btn-secondary' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 Iterations">
      <%= render collection: @active_iterations, as: :iteration, partial: 'iteration' %>
    </div>
  </div>
</div>